language: objective-c

notifications:
  email:
    on_success: never
    on_failure: dev@schrej.net

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

branches:
  only:
    - master
